# Generated by Django 4.0.3 on 2022-03-14 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(help_text='Enter your IIUI email address', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid IIUI email address', regex='^[\\w]+[\\w.%+-]*@iiu\\.edu\\.pk$')]),
        ),
    ]
