# Generated by Django 4.0.3 on 2022-03-04 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid IIUI email address', regex='^[\\w]+[\\w.%+-]*@iiu\\.edu\\.pk$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid Pakistan phone number', regex='^((\\+92)?(0092)?(92)?(0)?)(3)([0-9]{9})$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='registration_number',
            field=models.CharField(help_text='Please use the following format: <em>3958-FBAS/BSCS4/F18</em>.', max_length=6, unique=True),
        ),
    ]
