# Generated by Django 4.0.3 on 2022-03-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_profile_picture_alter_account_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='user',
            new_name='student',
        ),
    ]
