# Generated by Django 3.2.8 on 2022-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220301_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fatherName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
