# Generated by Django 4.0.3 on 2022-04-26 15:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.batch'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid Pakistan phone number', regex='^((\\+92)?(0092)?(92)?(0)?)(3)([0-9]{9})$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.programme'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='registration_number',
            field=models.CharField(help_text='Please use the following format: <em>3958</em>.', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.section'),
        ),
    ]
