# Generated by Django 4.0.3 on 2022-05-02 11:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', validators=[accounts.models.StudentProfile.validate_image]),
        ),
    ]
