# Generated by Django 3.2.8 on 2022-03-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_fathername'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
