# Generated by Django 4.0.3 on 2022-03-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_course_details_delete_session'),
        ('accounts', '0004_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fatherName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
