# Generated by Django 4.0.3 on 2022-03-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_session'),
        ('accounts', '0005_alter_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
