# Generated by Django 4.0.3 on 2022-05-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cnic',
            field=models.CharField(default='184962867493', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
