# Generated by Django 4.0.3 on 2022-05-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_cnic_studentprofile_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='cnic',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(max_length=20),
        ),
    ]
