# Generated by Django 4.0.3 on 2022-04-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studentprofile_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_completion',
            field=models.BooleanField(default=False),
        ),
    ]
