# Generated by Django 4.0.3 on 2022-05-21 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_studentprofile_cnic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(help_text='Please use the format: "+923456789121"', max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid Pakistan phone number', regex='^((\\+92))(3)([0-9]{9})$')]),
        ),
    ]
