# Generated by Django 4.0.3 on 2022-03-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0007_account_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='auth.permission'),
        ),
    ]
