# Generated by Django 4.0.3 on 2022-03-13 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0017_course_offered_in_semester_session_session_year_and_more'),
        ('accounts', '0015_remove_studentprofile_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='accounts.studentprofile')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='JoiningForm',
            fields=[
                ('parentform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submissions.parentform')),
                ('form_name', models.CharField(default='Joining Form', editable=False, max_length=30)),
                ('semester', models.PositiveSmallIntegerField(default=1, max_length=14)),
                ('course', models.ManyToManyField(blank=True, to='courses.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.session')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('submissions.parentform',),
        ),
    ]
