# Generated by Django 4.0.3 on 2022-05-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_session_batch_remove_session_courses_offered_and_more'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joiningform',
            name='form_name',
        ),
        migrations.AddField(
            model_name='joiningform',
            name='fee_slip',
            field=models.ImageField(blank=True, help_text='<strong>Note:<strong> Your form might get rejected if your fee slip is not attached', null=True, upload_to='forms/'),
        ),
        migrations.AddField(
            model_name='joiningform',
            name='reason',
            field=models.TextField(blank=True, help_text='Mention reason if rejected', null=True),
        ),
        migrations.AlterField(
            model_name='joiningform',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='courses.session'),
        ),
    ]
