# Generated by Django 4.0.3 on 2022-03-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_studentprofile_course'),
        ('submissions', '0002_rename_created_at_parentform_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentform',
            name='form_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', help_text="Change status to 'Accepted' if Student is eligible or 'Rejected' if not", max_length=12),
        ),
        migrations.AlterField(
            model_name='parentform',
            name='student',
            field=models.ForeignKey(help_text='Click above to get Student Info', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='accounts.studentprofile'),
        ),
    ]
