# Generated by Django 4.0.3 on 2022-03-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoiningForm',
        ),
    ]
