# Generated by Django 4.0.3 on 2022-05-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_profile_picture'),
        ('courses', '0002_remove_session_batch_remove_session_courses_offered_and_more'),
        ('submissions', '0003_alter_joiningform_course_alter_joiningform_fee_slip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoiningForm',
            new_name='Joining',
        ),
    ]
