# Generated by Django 4.0.3 on 2022-05-08 17:08

from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_session_batch_remove_session_courses_offered_and_more'),
        ('submissions', '0004_rename_joiningform_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joining',
            name='session',
            field=models.ForeignKey(default=submissions.models.get_latest_session, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='courses.session'),
        ),
    ]
