# Generated by Django 4.0.3 on 2022-05-14 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_joining_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joining',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(1)]),
        ),
    ]
