# Generated by Django 4.0.3 on 2022-07-22 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_studentprofile_phone_number'),
        ('courses', '0004_alter_session_session_name'),
        ('submissions', '0008_alter_joining_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joining',
            name='student',
            field=models.ForeignKey(help_text='Click above to get Student Info', on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile'),
        ),
        migrations.CreateModel(
            name='AddDropForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', help_text="Change status to 'Accepted' if Student is eligible or 'Rejected' if not", max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Mention reason if rejected', null=True)),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
                ('fee_slip', models.ImageField(blank=True, help_text='<strong>Note:</strong> Your form might get rejected if your fee slip is not attached', null=True, upload_to='AddDropForms/')),
                ('remarks', models.TextField(blank=True, help_text='Write your remarks if any', max_length=300, null=True)),
                ('add_course', models.ManyToManyField(blank=True, help_text='Add the course(s) to add, (leave blank if you only want to drop)', related_name='add_courses', to='courses.course')),
                ('drop_course', models.ManyToManyField(blank=True, help_text='Add the course(s) to drop, (leave blank if you only want to add)', related_name='drop_courses', to='courses.course')),
                ('session', models.ForeignKey(default=submissions.models.get_latest_session, on_delete=django.db.models.deletion.CASCADE, related_name='add_drop_session', to='courses.session')),
                ('student', models.ForeignKey(help_text='Click above to get Student Info', on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
