# Generated by Django 4.0.3 on 2022-07-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_session_session_name'),
        ('submissions', '0011_alter_adddropform_add_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddropform',
            name='add_course',
            field=models.ManyToManyField(blank=True, help_text='Add the course(s) to add, (leave blank if you only want to drop)', related_name='add_courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='adddropform',
            name='drop_course',
            field=models.ManyToManyField(blank=True, help_text='Add the course(s) to drop, (leave blank if you only want to add)', related_name='drop_courses', to='courses.course'),
        ),
    ]
