# Generated by Django 4.0.3 on 2022-07-24 14:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_session_session_name'),
        ('accounts', '0008_alter_studentprofile_phone_number'),
        ('submissions', '0013_alter_adddropform_add_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', help_text="Change status to 'Accepted' if Student is eligible or 'Rejected' if not", max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
                ('reason', models.TextField(blank=True, help_text='Mention reason if rejected', null=True)),
                ('petition_title', models.CharField(help_text='Write the title of your petition', max_length=100)),
                ('petition_description', models.TextField(help_text='Write the description of your petition', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2022, 8, 8, 14, 0, 20, 734764, tzinfo=utc), help_text='Set the date and time when the petition will expire')),
                ('session', models.ForeignKey(default=submissions.models.get_latest_session, on_delete=django.db.models.deletion.CASCADE, to='courses.session')),
                ('student', models.ForeignKey(help_text='Click above to get Student Info', on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
                ('student_signatures', models.ManyToManyField(blank=True, related_name='petition_signatures', to='accounts.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
