# Generated by Django 4.0.3 on 2022-08-06 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_petition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 16, 14, 0, 417738, tzinfo=utc), help_text='Set the date and time when the petition will expire'),
        ),
    ]
