# Generated by Django 4.0.3 on 2022-08-06 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_alter_adddropform_session_alter_joining_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 16, 36, 4, 885879, tzinfo=utc), help_text='Set the date and time when the petition will expire'),
        ),
    ]
