# Generated by Django 4.0.3 on 2022-04-29 14:47

import courses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_code', models.CharField(max_length=15, unique=True)),
                ('course_details', models.TextField(blank=True, null=True)),
                ('course_credit', models.IntegerField(default=3)),
                ('offered_in_semester', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Designates the semester in which the course is offered', null=True)),
                ('course_prerequisite', models.ForeignKey(blank=True, help_text='Select the prerequisite of the course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_course', to='courses.course')),
                ('course_programme', models.ManyToManyField(help_text='Select the programme(s) this course belongs to', to='accounts.programme')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(choices=[('Fall', 'Fall'), ('Spr', 'Spring'), ('Summer', 'Summer')], default='Fall', help_text='Please use the following format: <em>SPR-2022</em>.', max_length=20)),
                ('session_start_date', models.DateField(default=django.utils.timezone.now, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('session_year', models.PositiveSmallIntegerField(default=2022, help_text='Please use the following format: <em>20XX</em>.', validators=[django.core.validators.RegexValidator(message='Please enter a valid year', regex='^20[1-9][0-9]$')])),
                ('session_end_date', models.DateField(default=courses.models.get_session_end, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('joining_date', models.DateField(default=django.utils.timezone.now, help_text='Set the start of course joining.')),
                ('joining_deadline', models.DateField(default=courses.models.get_joining_deadline, help_text='Set the deadline of course joining for this session.')),
                ('batch', models.OneToOneField(help_text='Select the batch for which this session is being created.', on_delete=django.db.models.deletion.CASCADE, to='accounts.batch')),
                ('courses_offered', models.ManyToManyField(related_name='courses', to='courses.course')),
                ('programme', models.ForeignKey(help_text='Select the programme for which the session is being created.', on_delete=django.db.models.deletion.CASCADE, to='accounts.programme')),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type_name', models.CharField(max_length=80)),
                ('required_credits', models.IntegerField(blank=True, null=True)),
                ('course_type_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursetype'),
        ),
    ]
