# Generated by Django 4.0.3 on 2022-05-08 13:59

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='session',
            name='courses_offered',
        ),
        migrations.RemoveField(
            model_name='session',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='programme',
        ),
        migrations.AlterField(
            model_name='session',
            name='joining_deadline',
            field=models.DateField(default=courses.models.get_joining_deadline, help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
