# Generated by Django 4.0.3 on 2022-03-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='required_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
