# Generated by Django 4.0.3 on 2022-03-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_course_and_more'),
        ('courses', '0007_coursetype_required_credits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=20, unique=True)),
                ('session_start_date', models.DateField()),
                ('session_end_date', models.DateField()),
                ('courses_offered', models.ManyToManyField(to='courses.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.programme')),
            ],
        ),
    ]
