# Generated by Django 4.0.3 on 2022-03-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
