# Generated by Django 4.0.3 on 2022-03-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_end_date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(help_text='Please use the following format: <em>SPR-2022</em>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_start_date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
