# Generated by Django 4.0.3 on 2022-03-06 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_session_session_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='joining_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Set the start of course joining.', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='joining_end_date',
            field=models.DateField(blank=True, help_text='Set the end of course joining.', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='courses_offered',
            field=models.ManyToManyField(related_name='courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
