# Generated by Django 4.0.3 on 2022-03-07 11:18

import courses.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_session_joining_date_session_joining_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='joining_end_date',
        ),
        migrations.AddField(
            model_name='session',
            name='joining_deadline',
            field=models.DateField(default=courses.models.get_joining_deadline, help_text='Set the end of course joining.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Set the start of course joining.'),
        ),
    ]
