# Generated by Django 4.0.3 on 2022-03-07 11:26

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_session_joining_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_end_date',
            field=models.DateField(default=courses.models.get_session_end, help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
