# Generated by Django 4.0.3 on 2022-03-13 13:38

import courses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_studentprofile_course'),
        ('courses', '0016_alter_session_session_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offered_in_semester',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Designates the semester in which the course is offered', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_year',
            field=models.PositiveSmallIntegerField(default=2022, help_text='Please use the following format: <em>20XX</em>.', validators=[django.core.validators.RegexValidator(message='Please enter a valid year', regex='^20[1-9][0-9]$')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_prerequisite',
            field=models.ForeignKey(blank=True, help_text='Select the prerequisite of the course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_programme',
            field=models.ManyToManyField(help_text='Select the programme(s) this course belongs to', to='accounts.programme'),
        ),
        migrations.AlterField(
            model_name='session',
            name='batch',
            field=models.OneToOneField(help_text='Select the batch for which this session is being created.', on_delete=django.db.models.deletion.CASCADE, to='accounts.batch'),
        ),
        migrations.AlterField(
            model_name='session',
            name='joining_deadline',
            field=models.DateField(default=courses.models.get_joining_deadline, help_text='Set the deadline of course joining for this session.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='programme',
            field=models.ForeignKey(help_text='Select the programme for which the session is being created.', on_delete=django.db.models.deletion.CASCADE, to='accounts.programme'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spr', 'Spring'), ('Summer', 'Summer')], default='Fall', help_text='Please use the following format: <em>SPR-2022</em>.', max_length=20),
        ),
    ]
