# Generated by Django 4.0.3 on 2022-06-02 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='comment',
            field=models.ManyToManyField(blank=True, default=None, related_name='comment_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
