# Generated by Django 4.0.3 on 2022-06-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='comment',
        ),
    ]
