# Generated by Django 4.0.3 on 2022-06-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_remove_announcement_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(help_text='The post on which this comment exists', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='announcements.announcement'),
        ),
    ]
