# Generated by Django 4.0.3 on 2022-06-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_alter_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likedpost',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.DeleteModel(
            name='LikedComment',
        ),
        migrations.DeleteModel(
            name='LikedPost',
        ),
    ]
