# Generated by Django 4.0.3 on 2022-07-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_remove_likedpost_post_remove_likedpost_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
