# Generated by Django 4.0.3 on 2022-07-14 15:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
