# Generated by Django 4.0.3 on 2022-07-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_studentprofile_phone_number'),
        ('announcements', '0009_alter_announcement_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.batch')),
            ],
        ),
    ]
