# Generated by Django 4.0.3 on 2022-07-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_studentprofile_phone_number'),
        ('announcements', '0010_sendsms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendsms',
            name='batch',
        ),
        migrations.AddField(
            model_name='sendsms',
            name='batch',
            field=models.ManyToManyField(blank=True, default=None, to='accounts.batch'),
        ),
    ]
