# Generated by Django 4.0.3 on 2022-07-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0012_announcement_subscribed_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Announcement Subscribers',
            },
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='subscribed_students',
        ),
    ]
